version: 1
disable_existing_loggers: true

formatters:
    standard:
        format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s"
        datefmt: "%Y-%m-%d %I:%M:%S"
    error:
        format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: app/logs/app.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    file_db_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: app/logs/app_db.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: DEBUG
    handlers:
        - console
        - file_handler

loggers:

    sqlalchemy:
        level: INFO
        handlers:
            - console
            - file_db_handler
        propagate: false

    uvicorn:
        level: DEBUG
        handlers:
            - console
            - file_handler
        propagate: false

    uvicorn.error:
        level: INFO
        formatter: standard
        handlers:
            - console
            - file_handler
        propagate: false

    uvicorn.access:
        level: INFO
        handlers:
            - console
            - file_handler
        propagate: false