version: 1
disable_existing_loggers: true

formatters:
  standard:
    format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s"
    datefmt: "%Y-%m-%d %I:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: ./../src/logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

root:
  level: DEBUG
  handlers:
    - console
    - file_handler

loggers:
  sqlalchemy:
    level: INFO
    propagate: true

  uvicorn:
    level: DEBUG
    propagate: true

  uvicorn.error:
    level: INFO
    propagate: true

  uvicorn.access:
    level: INFO
    propagate: true
