"""create_secret_table

Revision ID: 80f216f08b36
Revises:
Create Date: 2025-04-29 21:06:04.267440

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '80f216f08b36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'secret',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            'secret', sqlmodel.sql.sqltypes.AutoString(length=65536), nullable=False,
        ),
        sa.Column(
            'hashed_password',
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column('reg_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('secret', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secret_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secret', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secret_id'))

    op.drop_table('secret')
    # ### end Alembic commands ###
